### ISSUE TITLE
1st Data Package: 03 Exposure Layers

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/data-package#10]
Create Population Exposure Layers and make them available in CSIS. 
This encompasses the following steps:
- [x] provide population exposure data (PLINIVUS?)
- [x] transformation to the [harmonised Grid](https://github.com/clarity-h2020/csis/issues/42)
- [x] expose Layers (WCS/WMS) via GeoServer (currently located at **METEOGRID** Server)
- [x] define some simple styling for Layers
- [ ] Create Data Package Meta-Data in CSIS (see also https://github.com/clarity-h2020/data-package
/issues/7)
- [ ] Provide meta-data for [Data Management Plan](https://github.com/clarity-h2020/ckan/milestone/1) (if not already available from D2.2 activities)

**Questions:**
- ATM we've got only population exposure for the Naples reference region coming from WP2, right?
- Where can I find the respective meta-data? Is it available in CKAN?

**Comment by p-a-s-c-a-l** [comment]
What is the status here? There are 3 Population Layers available for DC1 on METEOGRID GeoServer. @bernhardsk Are those the same that are used for impact calculation in EMIKAT?

**Comment by humerh** [comment]
As described in my last mail: YES!!

Von: Pascal Dihé <notifications@github.com>
Gesendet: Montag, 25. Februar 2019 09:04
An: clarity-h2020/data-package <data-package@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: Re: [clarity-h2020/data-package] 1st Data Package: 03 Exposure Layers (#10)


What is the status here? There are 3 Population Layers available for DC1 on METEOGRID GeoServer. @bernhardsk<https://github.com/bernhardsk> Are those the same that are used for impact calculation in EMIKAT?

**Comment by maesbri** [comment]
@ghilbrae , in order to add these population exposure layers (https://clarity.meteogrid.com/geoserver/Exposure/wcs?request=GetCapabilities) in the data package I need the following information:
- what is origin source used to make the calculations
- what is the time frame (temporal extent) for which this data refers to?

**Comment by ghilbrae** [comment]
@maesbri I'll check with my colleagues and will come back with an answer.

**Comment by ghilbrae** [comment]
> 
> * what is origin source used to make the calculations

It seems the source is a layer uploaded to ATOS' FTP by @negroscuro 
> * what is the time frame (temporal extent) for which this data refers to?

They refer to the current state.

**Comment by maesbri** [comment]
> > * what is origin source used to make the calculations
> 
> It seems the source is a layer uploaded to ATOS' FTP by @negroscuro
> 
That's too vague ... I need to add the concrete reference to the layers used (preferrrably the link to the Geoserver layer)

> > * what is the time frame (temporal extent) for which this data refers to?
> 
> They refer to the current state.
Once I know the layers I can check their metadata for the time range

**Comment by stefanon** [comment]
@maesbri  Dear Miguel, 
about exposure data, the layer you were talking about was result of elaboration starting from ISTAT population census data tables. You'll find the "ISTAT census data - population " dataset description in CKAN.   
>   what is origin source used to make the calculations 
>
That was the source, but population data needed to be related to the geographic census zones and EU grid, the work was done by METEOGRID 
>   what is the time frame (temporal extent) for which this data refers to?
>
the population data refers to year 2011 as in CKAN description.

**Comment by maesbri** [comment]
@therter , I have now updated the naples data package with the 3 resources referring to the population exposure (they are linked to the eu-gl step "exposure evaluation", let me know if they should refer to additional eu-gl steps too).

**Comment by therter** [comment]
@maesbri The resource with the url https://csis.myclimateservice.eu/node/434 has no mapview property. Is this correct? 

And the resource https://csis.myclimateservice.eu/node/409 has also no mapview attribute

**Comment by maesbri** [comment]
I forgot to fill in those fields. It should be fixed now :)

**Comment by p-a-s-c-a-l** [comment]
Exposure Data (Population) for whole Europe will be served from [a new EMIKAT API](https://github.com/clarity-h2020/emikat/issues/10). The Data Package and the [table rest API](https://github.com/clarity-h2020/table-state-rest-api/issues/7) have to be updated accordingly.

**Comment by p-a-s-c-a-l** [comment]
The EE  Resources in this Data Package Package currently contain [**Local** Census Data](https://csis.myclimateservice.eu/node/434) - Population for the Naples Region from ISTAT (Italian National Institute of Statistics). These resources will be moved to a new DC1 Data Package that is available for [subscribers](https://github.com/clarity-h2020/docker-drupal/issues/82) only! The current resources are replaced with the Europe-Level Population exposure data from Copernicus.

**Comment by p-a-s-c-a-l** [comment]
Population Exposure Data is avilable in EMIKAT: https://github.com/clarity-h2020/emikat/issues/10#issuecomment-510068266
The resources have to be updated accordingly.

**Comment by DenoBeno** [comment]
@Heinrich: Pascal says that the population data is in EMIKAT now? Is this correct?

**Comment by humerh** [comment]
The population exposure layer is accessible at:

https://service.emikat.at/EmiKatTst/api/scenarios/2846/feature/tab.CLY_EL_POPULATION_INTERPOLATED.2016/table/data?rownum=1000

emikatID=2846

**Comment by humerh** [comment]
We use the Populationen Data from EUROSTAT (1km*1km) and split this data to the 500m-Grid by using Landcover data from Copernicus. This data are available for all Europe.

**Comment by DenoBeno** [comment]
I have added "European population distribution" resource to European data package now. 

https://csis.myclimateservice.eu/node/682/edit#browser

Issues:

1) I don't know what is the license for this data. If it's based on EUROSTAT and COPERNICUS, 

- Land cover COPERNICUS data has this license: https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX%3A32013R1159 (In short https://land.copernicus.eu/faq/about-data-access)
- EUROSTAT: https://ec.europa.eu/eurostat/about/policies/copyright

This are both "use as you want, but inform people that it's from us and that you have modified it (if applicable)". I explained this in the description and choose three different licenses for the data resource:
![image](https://user-images.githubusercontent.com/2961790/62138431-ede66680-b2e7-11e9-90fa-8c5859e924a8.png)

Furthermore, there are several paths to this resource, as explained in https://github.com/clarity-h2020/emikat/issues/10

Additional Services available:
EMIKAT REST: https://service.emikat.at/EmiKatTst/api/scenarios/2846/feature/tab.CLY_EL_POPULATION_INTERPOLATED.2016/table/data?rownum=1000

or EMIKAT GeoJSON: https://service.emikat.at/EmiKatTst/api/scenarios/2846/feature/tab.CLY_EL_POPULATION_INTERPOLATED.2016/table/geojson?rownum=1000

or CSV: https://service.emikat.at/EmiKatTst/api/scenarios/2846/feature/tab.CLY_EL_POPULATION_INTERPOLATED.2016/table/csv?rownum=1000

or WMS:
WMS: https://service.emikat.at/geoserver/clarity/wms?service=WMS&version=1.1.0&request=GetMap&layers=clarity:view.2955&bbox=4673500.0,1980000.0,4691500.0,1988000.0&width=768&height=341&srs=EPSG:3035&format=image/gif&CQL_FILTER=SZ_ID=2846

Now, I have added them all, but what are the service types for the first three? :-(

**Comment by DenoBeno** [comment]
Furthermore, I run into a strange bug shown here: 

![image](https://user-images.githubusercontent.com/2961790/62138941-ce037280-b2e8-11e9-9442-00f8882f48b9.png)

This is probably due to automated title generation. I propose to let the user define a title - at least we could then Call these references "European population data - EMIKAT GeoJSON" or such.

**Comment by DenoBeno** [comment]
Furthermore, the EMIKAT data access is password protected. How is this supposed to work in the DP?

**Comment by humerh** [comment]
You inserted this Path:
https://service.emikat.at/EmiKatTst/api/scenarios/2846/feature/tab.CLY_EL_POPULATION_INTERPOLATED.2016/table/data?rownum=1000

Instead of the fixed ID 2846  there should be a placeholder for the emikatId, which is an attribute in the study.

Maybe the path should be replaced to:
https://service.emikat.at/EmiKatTst/api/scenarios/$emikatId/feature/tab.CLY_EL_POPULATION_INTERPOLATED.2016/table/data?rownum=1000

@maesbri can you clarify this?

**Comment by humerh** [comment]
The password has to be provided by "Basic Authentication" Header.

**Comment by p-a-s-c-a-l** [comment]
> Furthermore, the EMIKAT data access is password protected. How is this supposed to work in the DP?

There is currently a temporary workaround implemented (basic auth) since offering [Single-Sign-On](https://github.com/clarity-h2020/docker-drupal/issues/16) seems to be stalled.

**Comment by p-a-s-c-a-l** [comment]
- The respective **Population Exposure** Resource is described [here](https://github.com/clarity-h2020/data-package/issues/49)
- Flood (Buildings?) Exposure resources still pending

**Comment by DenoBeno** [comment]
Indeed, we need buildings exposure for the flooding. Not sure what all goes under "buildings" though. Are we going to have separate layers for the different types of buildings?

**Comment by p-a-s-c-a-l** [comment]
**Population** Exposure Layers available for 1st data package. Flood is a different issue.
