### ISSUE TITLE
1st Data Package: 02 Hazard Local Effects Layers for Heat Waves

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/data-package#11]
Create Hazard Local Effects Layers and make them available in CSIS. 

This encompasses the following steps:
- [x] ZAMG to provide plain HC Data: **done**. [netcdf avialble on sftp](https://github.com/clarity-h2020/data-package/issues/8#issuecomment-444859213)
- [x] METEOGRID to [create HC-LE layers](https://github.com/clarity-h2020/csis/issues/33) based on input layers prepared by ATOS
- [x] METEOGRID to [expose Layers (WCS/WMS) via their GeoServer](https://github.com/clarity-h2020/data-package/issues/8#issuecomment-444859213)
- [x] METEOGRID to define some simple styling for Layers (no need to consider thresholds as explained [here](https://github.com/clarity-h2020/data-package/issues/8#issuecomment-444499328))
- [ ] CIS to [create Data Package Meta-Data in CSIS](https://github.com/clarity-h2020/data-package/milestone/1)
- [ ] ??? to provide meta-data for [Data Management Plan](https://github.com/clarity-h2020/ckan/milestone/1)<br>Both HC-LE and respective *input layers* are open data that eventually to deposited in zenodo (if we have calculated the HC-LE data for whole Europe)

**Important Notes:**
- This tasks depends on [Hazard Local Effects Modelling Workflow Implementation](https://github.com/clarity-h2020/csis/issues/33), currently HC-LE Data is not yet available!
- The [Impact Model](https://github.com/clarity-h2020/csis/issues/22) shall use HC-LE Data (500m grid), **not** plain [HC Data](https://github.com/clarity-h2020/data-package/issues/8) (12.5km grid)
- There is already MUKLIMO HC data available for Naples. Although this data is meant for the **Expert Workflow**, we could use it temporarily in the screening workflow as substitute for the HC-LE data which yet has to be calculated.

**Comment by p-a-s-c-a-l** [comment]
Could somebody please update the status?  E.g. AFAIK [HC-LE HW Layers](https://github.com/clarity-h2020/csis/issues/33) are now available for all HC HW Layers from [clarity.meteogrid.com](https://clarity.meteogrid.com/geoserver/web/wicket/bookmarkable/org.geoserver.web.demo.MapPreviewPage?1).

**Comment by maesbri** [comment]
Currently, in Meteogrid's Geoserver there are these Local Effects layers:
- clarity__Heat_wave_temperature_historical_hight_hazard_Naples
- clarity__Heat_wave_temperature_historical_low_hazard_Naples
- clarity__Heat_wave_temperature_historical_medium_hazard_Naples
- clarity__Heat_wave_temperature_historical_very_hight_hazard_Naples


@ghilbrae , for each of them I need the following metadata information in order to properly describe them within the Naples data package I am preparing (see https://github.com/clarity-h2020/data-package/blob/master/examples/dc1-naples/datapackage.json):
- title (not the layer name)
- brief description
- temporal extent (starting and ending time periods that are comprehended by this resource)
- sources of the data used for the calculation of this resource
- temperature

**Comment by p-a-s-c-a-l** [comment]
This information should be in our CKAN: https://ckan.myclimateservice.eu/dataset/historical-heat-wave-temperature-local-effects

**Comment by maesbri** [comment]
yes, I had already checked it but the information required is not there

**Comment by ghilbrae** [comment]
@maesbri I'll check with my colleagues and come back with an answer for you.

**Comment by ghilbrae** [comment]
> Currently, in Meteogrid's Geoserver there are these Local Effects layers:
> 
> * clarity__Heat_wave_temperature_historical_hight_hazard_Naples
> * clarity__Heat_wave_temperature_historical_low_hazard_Naples
> * clarity__Heat_wave_temperature_historical_medium_hazard_Naples
> * clarity__Heat_wave_temperature_historical_very_hight_hazard_Naples
> 
> @ghilbrae , for each of them I need the following metadata information in order to properly describe them within the Naples data package I am preparing (see https://github.com/clarity-h2020/data-package/blob/master/examples/dc1-naples/datapackage.json):
> 
> * title (not the layer name)

![image](https://user-images.githubusercontent.com/1615745/54112101-b719bd80-43e5-11e9-94af-cc95c784ded2.png)

> * brief description

Heat Wave Hazard in Napoli considering different base Temperatures.
> * temporal extent (starting and ending time periods that are comprehended by this resource)

Baseline for current time.
> * sources of the data used for the calculation of this resource

The resource was generated based on the data generated/downloaded by ATOS.
> * temperature

Base temperatures are: 32 (low), 34 (medium), 36 (high) and 38 (very high).

**Comment by maesbri** [comment]
> > Currently, in Meteogrid's Geoserver there are these Local Effects layers:
> > 
> > * clarity__Heat_wave_temperature_historical_hight_hazard_Naples
> > * clarity__Heat_wave_temperature_historical_low_hazard_Naples
> > * clarity__Heat_wave_temperature_historical_medium_hazard_Naples
> > * clarity__Heat_wave_temperature_historical_very_hight_hazard_Naples
> > 
> > @ghilbrae , for each of them I need the following metadata information in order to properly describe them within the Naples data package I am preparing (see https://github.com/clarity-h2020/data-package/blob/master/examples/dc1-naples/datapackage.json):
> > 
> > * title (not the layer name)
> 
> ![image](https://user-images.githubusercontent.com/1615745/54112101-b719bd80-43e5-11e9-94af-cc95c784ded2.png)
> 
> > * brief description
> 
> Heat Wave Hazard in Napoli considering different base Temperatures.
> 
> > * temporal extent (starting and ending time periods that are comprehended by this resource)
> 
> Baseline for current time.

What is the current time? 2019? The date time of the original temperature data used for the calculations?

> 
> > * sources of the data used for the calculation of this resource
> 
> The resource was generated based on the data generated/downloaded by ATOS.
> 
Again, too vague. We need the concrete references to the data sources used. For temperature data, which were your sources, EURO-CORDEX?

> > * temperature
> 
> Base temperatures are: 32 (low), 34 (medium), 36 (high) and 38 (very high).
ok, thanks. I would suggest to rename the layers in your geoserver by replacing "low", medium", etc. by the temperature degrees as the naming used looks to me subjective (32ºC can be low for Naples but very high for other European regions)

**Comment by p-a-s-c-a-l** [comment]
IMHO the wrong resources (HC-LE Input Layers) are currently referenced in the [Naples DataPackage](https://csis.myclimateservice.eu/node/221). This is also related to https://github.com/clarity-h2020/csis/issues/22#issuecomment-472863700 and https://github.com/clarity-h2020/map-component/issues/15

**Comment by therter** [comment]
@maesbri @ghilbrae The wms layer for Historical heat wave temperature in Naples (34ºC)(local effects) (Local_Effects:Heat_wave_temperature_historical_very_hight_hazard_Naples) does not exist in the wms. So the map-component cannot show this layer.

**Comment by p-a-s-c-a-l** [comment]
As agreed with @humerh Local Effects Hazard Layers which are based on Events chosen by the user for whole Europe will be served from EMIKAT API! The Data Package has to be updated accordingly. The EMIKAT API for hazard with local effects events will be accessed by parametrised URLs. Parameters are project id (=study id), study area bbox, event type (frequen, occasional, rare), RCP and time period. EMIKAT will then return hazard values for the table component (preferably in JSON or CSV) and for the Map Component (WMS). 

We need only one HC-LE resource per Hazard type. The resource contains two different URLs (references), one for map request (WMS) and one for table data (REST/JSON). The URLs support parameters e.g. $studyId, $studyArea, $hazardType, $rcp, $TimePeriod which are replaced by the ReactJS Components (table and map) by actual values extracted from the study context (obtained via Drupal JSON API). Furthermore, the user [has to chose](https://github.com/clarity-h2020/docker-drupal/issues/58) a one event from the baseline and one corresponding event from a specific RCP / time period.

The Data Package / HC-LE Resources has to be updated accordingly once @humerh provided sample, request URIs for the EMIKAT API.

**Comment by p-a-s-c-a-l** [comment]
> Parameters are project id (=study id), study area bbox, event type (frequen, occasional, rare), RCP and time period.

> The URLs support parameters e.g. $studyId, $studyArea, $hazardType, $rcp, $TimePeriod which are replaced by the ReactJS Components (table and map) by actual values extracted from the study context (obtained via Drupal JSON API).

Alternatively, instead of sending $hazardType, $rcp, $timePeriod to the EMIKAT API for Impact Calculation, we could send two `$eventId`s: One for the baseline and a corresponding one ogf the same type (frequent || occasional || rare) chosen by the user in the [Scenario Selection UI](https://github.com/clarity-h2020/docker-drupal/issues/58).

**Comment by RobAndGo** [comment]
As suggested by @p-a-s-c-a-l I have moved this comment from #4 to here.

Here are the data package json files for the 
- summer days 
- hot days
- tropical nights

hazard characterisation indices on the European level. I had to include the suffix .txt in order that github allowed me to upload the files.

[data_package_heat_indices_summer_days.json.txt](https://github.com/clarity-h2020/data-package/files/3346239/data_package_heat_indices_summer_days.json.txt)
[data_package_heat_indices_hot_days.json.txt](https://github.com/clarity-h2020/data-package/files/3346236/data_package_heat_indices_hot_days.json.txt)
[data_package_heat_indices_tropical_nights.json.txt](https://github.com/clarity-h2020/data-package/files/3346238/data_package_heat_indices_tropical_nights.json.txt)

Each resource within the data package gives the:
a) model ensemble mean (odd numbered resources)
b) model standard deviation (even numbered resources)
for each of the periods:

baseline period (1971-2000)
rcp26 (2011-2040, 2041-2070, 2071-2100)
rcp45 (2011-2040, 2041-2070, 2071-2100)
rcp85 (2011-2040, 2041-2070, 2071-2100)
That is, there are a total of 20 resources within each data package.

I have uploaded the corresponding data here:
/clarityftp/europe/hazard_indices/heat/summerdays/
/clarityftp/europe/hazard_indices/heat/hotdays/
/clarityftp/europe/hazard_indices/heat/tropicalnights/

**Comment by p-a-s-c-a-l** [comment]
- the respective **Heat Hazard** HC-LE Resource is described [here](https://github.com/clarity-h2020/data-package/issues/45).
- **Flood Hazard** HC-LE Resource still pending

**Comment by DenoBeno** [comment]
As discussed today: For the flood hazard, we should at most put out few example resources until we can define the resources to work with variables.

maybe we should rename this into "...for heat". close it and open a new issue for the flood hazard?
