### ISSUE TITLE
1st Data Package: 00 Background Layers - 2) Create Data Resource

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/data-package#7]
For the Background Layers created in https://github.com/clarity-h2020/data-package/issues/5, the respective [Data Resource](https://github.com/clarity-h2020/data-package/wiki/Specification:-CLARITY-Data-Resource) entities of the [1st Data Package](https://github.com/clarity-h2020/data-package/milestone/1) have to be created [in CSIS](https://csis.myclimateservice.eu/node/add/data_package_metadata).

Important properties:

- the [link](https://docs.google.com/spreadsheets/d/10ii3Exq3SSkz5nmiUwRenumnhfw1h13_M5_FcKFha7Y/edit#gid=71709484&range=A16) property should point URI of the layer. @maesbri Question: How do we deal with different representations of the same dataset, e.g. WFS, WMS URL, ShapeFile download, etc.?
- the [resource_type](https://docs.google.com/spreadsheets/d/10ii3Exq3SSkz5nmiUwRenumnhfw1h13_M5_FcKFha7Y/edit#gid=71709484&range=A46) property of the Data Resource's **Analysis Context** must be set to *background layer*
- the [workflow_step](https://docs.google.com/spreadsheets/d/10ii3Exq3SSkz5nmiUwRenumnhfw1h13_M5_FcKFha7Y/edit#gid=71709484&range=A48) property of the **Analysis Context** should be provided (if possible), so that the [Map Component](https://github.com/clarity-h2020/map-component) can decide whether the background layer is shown in a specific analysis context or not.

This task depends partially on https://github.com/clarity-h2020/data-package/issues/12

**Comment by p-a-s-c-a-l** [comment]
Background Layers are available in HC-LE.

**Comment by p-a-s-c-a-l** [comment]
- [x] create new [DP_ResourceType](https://csis.myclimateservice.eu/admin/structure/taxonomy/manage/dp_resourcetype/overview)
- [x] implement [Support for Template Resources](https://github.com/clarity-h2020/map-component/issues/69) in Map Component.
- [x] Create Background **Template Resources** for [Urban Atlas WMS Layers](https://image.discomap.eea.europa.eu/arcgis/services/UrbanAtlas/UA_UrbanAtlas_2012/MapServer/WMSServer)

**Comment by p-a-s-c-a-l** [comment]
- [ ] check https://discomap.eea.europa.eu/Index/ and add more useful background layers

**Comment by p-a-s-c-a-l** [comment]
Added [Urban Sprawl Europe 2009 1km LEAC GRID level](https://csis.myclimateservice.eu/node/2069): [Map](https://csis.myclimateservice.eu/apps/map-component/build/?url=https://csis.myclimateservice.eu&resource_uuid=621a1895-f9dd-4813-96b9-4071be22109e)

**Comment by p-a-s-c-a-l** [comment]
Done. Most interesting [EEA Discover Map Services](https://csis.myclimateservice.eu/apps/map-component/build/?url=https://csis.myclimateservice.eu&resource_uuid=83ce0b58-58de-4bc7-821c-48aa939c6b45) added.
