### ISSUE TITLE
1st Data Package: 01 HC Layers

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/data-package#8]
Create Layers for [Hazard Indices calculated by ZAMG](https://github.com/clarity-h2020/ckan/issues/9#issue-383829684) and make them available in CSIS. 

This encompasses the following steps (to be confirmed / updated by @clarity-h2020/data-processing-team):
- [x] provide original HW hazard indexes for 1+3 time periods and 3 RCPs.
  - **available here**: sftp://5.79.69.49/clarityftp/europe/hazard_indices/heat/heat-wave-duration/Index_Tx75p/
- [x] transformation to the [harmonised Grid](https://github.com/clarity-h2020/csis/issues/42)
- [x] expose Layers (WCS/WMS) via GeoServer (currently located at **METEOGRID** Server)
  - **available here**: https://clarity.meteogrid.com/geoserver/web/wicket/bookmarkable/org.geoserver.web.demo.MapPreviewPage?2
- [x] define some simple styling for Layers
  - **not yet available**
- [x] Create Data Package Meta-Data in CSIS (see also #7 and #12)
  -   **not yet available**
- [x] Provide meta-data for [Data Management Plan](https://github.com/clarity-h2020/ckan/milestone/1)
  - **not yet available**

Questions:
- those layers are not used *directly* for impact calculation, right? Main purpose is visualisation in CSIS Map & Table View and input for Hazard Local Effects.
- is the grid transformation necessary or is the input data (NetCDF) already in the correct grid / projection?
- can the transformation / postgis import / geoserver layer generation be automated by some scripts? HC Layers need to be generated for Europe (screening), 4 DCs and when ZAMG has [re-calculated](https://github.com/clarity-h2020/ckan/issues/9#issuecomment-442056862) the indices based on bias corrected data.
- who is responsible for this tasks? ATOS, METEOGRID, AIT?
- how and for which purpose is the data accessed by the impact model service (Emikat)? CSW or direct data base access (preferable)? Only together with a "differential layer" (from local effects) as inmput for HxExV?

Additionally, [Map Visualisation](https://github.com/clarity-h2020/map-component/issues/2), Table Visualisation and [Report Generation](https://github.com/clarity-h2020/docker-drupal/issues/20) have to be implemented.

**Comment by stefanon** [comment]
> those layers are not used directly for impact calculation, right? Main purpose is visualisation in CSIS Map & Table View and input for Hazard Local Effects.

yes

> is the grid transformation necessary or is the input data (NetCDF) already in the correct grid / projection?

~~for what I've seen ZAMG NetCDFs are in EPSG:3035 alias ETRS89 / ETRS-LAEA .~~ The raster pixel size is way bigger of the base 500x500m grid.

> can the transformation / postgis import / geoserver layer generation be automated by some scripts? HC Layers need to be generated for Europe (screening), 4 DCs and when ZAMG has re-calculated the indices based on bias corrected data.

Postgis import can be script automated, trasformations can be done in PostgreSQL/PostGIS PL/PgSQL procedures, Geoserver publication can be scripted by means of the Geoserver REST API.

**Comment by ghilbrae** [comment]
Answer in agreement with @luis-meteogrid 

> Create Layers for Hazard Indices calculated by ZAMG and make them available in CSIS.
> 
Not only direct Hazard indexes but also, the CSIS needs to have the Local Effects in the Hazard indexes layers. As agreed in the Plenary Meeting, **Meteogrid** is responsible of doing this calculation.

> This encompasses the following steps (to be confirmed / updated by @clarity-h2020/data-processing-team):
> 
>   transformation to the harmonised Grid

We intend to do the calculations in the original grid and, as a last step, to transform everything to the agreed upon grid. ZAMG's original grid has EPSG 4326 instead of 3035, as expected by AIT. We can re-project and fit the results to the expected resolution.

>   import into PostgreSQL Database (currently located at ATOS Server)
>   expose Layers (WCS/WMS) via GeoServer (currently located at ATOS Server)

We were planning on using our instance of GeoServer located in the server in which we are going to perform the calculations for the Local Effects. Please, be aware that the Local Effects might need to be re-calculated on-the-fly if the user modifies the distribution of Urban Elements.
The layers will be exposed as raster files with 3035 projection using the reference grid provided by AIT. This includes both the re-projection of ZAMG's hazard indexes as well as the local effects. This will be done for other layers, such as Population Layer, that AIT might need.

>   style Layers according to Hazard Thresholds

This might be done at the visualization level or be attached to the layer if someone is able to provide the thresholds beforehand. We have a tool that already does this running on a django app.

>   Create Data Package Meta-Data in CSIS (see also https://github.com/clarity-h2020/data-package
> /issues/7)
>   Provide meta-data for Data Management Plan
> Questions:
> 
> those layers are not used directly for impact calculation, right? Main purpose is visualisation in CSIS Map & Table View and input for Hazard Local Effects.

From our POV, the main purpose is calculation of Local Effects as well as visualization. So, yes.

> is the grid transformation necessary or is the input data (NetCDF) already in the correct grid / projection?

A transformation is necessary, the original data do not have the correct projection, grid nor the resolution.

> can the transformation / postgis import / geoserver layer generation be automated by some scripts? HC Layers need to be generated for Europe (screening), 4 DCs and when ZAMG has re-calculated the indices based on bias corrected data.

The main goal is to automate most of the process, we'll have to see if it is achievable at a 100%. For the Local Effects calculations we are using our own framework to achieve this automation, both for the calculations, re-projection and interpolation.

> who is responsible for this tasks? ATOS, METEOGRID, AIT?

We can take charge of the first steps, up until the Local Effects generation. AIT seems to be responsible from that step onward. If there's any problem with visualization we can agree on some sort of common solution.

> how and for which purpose is the data accessed by the impact model service (Emikat)? CSW or direct data base access (preferable)? Only together with a "differential layer" (from local effects) as inmput for HxExV?
> Additionally, Map Visualisation, Table Visualisation and Report Generation have to be implemented.

We understood that report generation was going to fall on Drupal's side. 

As for the other two, it will depend on what this might entail, we already have some tools for map visualization, if they can be reused for this we could try and see how to provide some sort of communication between them, it would also depend on the ease of communication with drupal or/and emikat or any other tools. 

Just to be clear, we are not going to develop on drupal, but we are willing to help with other tools to access data (tables), layers or maps.

**Comment by p-a-s-c-a-l** [comment]
Ok, Thanks!

In this issue, I care mainly about the original hazard Data, Local Effects will be addressed / discussed separately. 

So AIT & ATOS are not directly involved in the "plain" HC task. The demo Hazard Layers on ATOS server will not be used in CSIS or for any HC-LE or RA/IA calculation. Agreed @bernhardsk @humerh & @negroscuro ?

In summary, the responsibilities are
- METEOGRID will do the reprojection of ZAMG's Hazard NetCDF files from WGS84 (EPSG:4326) 0.11 degree (EUR-11, ~12.5km) grid to ETRS89 LEA (EPSG:3035) 500x500m grid and make the layers available for visualisation via their own geoserver instance (https://clarity.meteogrid.com/geoserver/). 
- CIS will create the Data Package Meta-Data in CSIS and show the layer on a (simple) Map. Of course, since no downscaling is performed yet, the 500x500m layer will still show just a 12x12km grid.
- CIS will add the respective Datasets (meta-data) to CKAN for the Data Management Plan

Open Issues:
- [x] Atm, there is just one WMS Layer for Heatwave Duration Hazard for RCP2.6 and period 2011-01-01 - 2040-12-31 available and the layer is missing a proper style. For a realistic demo **some simple styling must be defined** and the Heatwave Layers for the remaining RCPs and time periods (@astridkainz should upload them to the sFTP server) should be added. 
- [x] For tabular visualisation we would need access to the actual values of all grid cells in the study area. How the values are aggregated and mapped to thresholds (good, average, bad) will be addressed in a separate Issue. Probably, this can be done on client-side, so access via e.g. WFS would be sufficient in the first place.

**Comment by RobAndGo** [comment]
Hello,
@astridkainz forwarded me the link to this discussion, so I'm just joining in now.

I have uploaded 2 zip files here:
[https://repository.atosresearch.eu/owncloud/index.php/apps/files?dir=/CLARITY/WP3%20Science%20Support/T3.2%20Climate%20Intelligence/Data]

Sorry if it is not the new way to upload files, but I didn’t have time to look into the CKAN/ATOS ftp server thingy.

These files are in the native netcdf EURO-CORDEX rotated grid projection. @luis-meteogrid you said it was no problem for you to convert it into a useable projection.

All of this data is to do with the climate index “Tx75p” which is a measure for heat wave duration. In detail, the index is:
“Maximum number of consecutive days with a daily maximum temperature ≥ 75th percentile of daily maximum temperatures in the period April – Sept (1971 – 2000).”

The file HazardMap_Tx75p.zip contains 9 layers for Tx75p for:
- RCPs 2.6, 4.5, 8.5
- Time periods 2011-2040, 2041-2070, 2071-2100
These files show the hazard scale as 1=low, 2=medium, 3=high.

The file also contains a text file describing the rule I used to define the low/medium/high hazard levels. 
“
_The final signal is represented as an index of 1, 2, 3 (low, medium, high) according to:
1 - increase < 50 %
2 - increase >= 50 %, increase < 100 %
3 - increase >= 100 %_
“
@p-a-s-c-a-l: is this what you mean by “style” in your comment of “**some simple styling must be defined**”?

The raw index values of Tx75p are in the file Index_Tx75p.zip. These values are the actual index values and would/could be used when implementing the method created by PLINIVS.

I hope this helps!

**Comment by astridkainz** [comment]
We've also prepared an updated example for the tabular visualisation of hazards: 

![hazard_table_new](https://user-images.githubusercontent.com/45257378/49516211-613ef200-f899-11e8-8ec4-75cceef29588.png)

In particular, we need to make sure that their is a clear distinction between the reference period (baseline) and the future scenarios, mainly because the respective hazard scales are defined differently. 

A pull-down menu could be provided to let the user switch between different future periods, as suggested by Denis.

**Comment by p-a-s-c-a-l** [comment]
> @p-a-s-c-a-l: is this what you mean by “style” in your comment of “**some simple styling must be defined**”?

Hm, the 'original' indexes range from 5,433333 to 41,63334 (days). IMHO we don't need the additional hazard maps with 'normalised' indexes (1 to 3, low, medium, high), but just the thresholds (e.g. x = 8 and y = 14) to perform the normalisation just in time when we render the maps and the tables.

@clarity-h2020/data-processing-team With help a of a styled layer descriptor it would be possible to map the original indexes (5,4 - 41,6) to 1,2,3 (green, yellow, red) when absolute values for x and y are know, right? On the other hand, I think we should show the original indexes in the map and the normalised indexes just in the table. Reason: The user can recognise slight differences between adjacent grid cells, especially when taking local effects in to account (500x500m grid). If we just show values ranging from 1-3 in the map, probably no difference between HC and HC-LE would be recognisable.

@clarity-h2020/mathematical-models-implementation-team: for impact calculation you would need the original indexes anyway? 

So at the moment I don't see a need to store them twice in the database / geoserver.  

### Map comparison: orginal vs normalised:

![tx75p_consecutive_max_in_tx75p_consecutive_max_eur-11_ichec-ec-eart](https://user-images.githubusercontent.com/1788226/49519309-fb566880-f8a0-11e8-9e39-fd560213356e.png)
![tx75p_consecutive_max_in_tx75p_consecutive_max_eur-11_ichec-ec-eart_2](https://user-images.githubusercontent.com/1788226/49519310-fbeeff00-f8a0-11e8-8930-e92810b3004a.png)

@ghilbrae Could you please transform the ncfd files (sftp://5.79.69.49/clarityftp/europe/hazard_indices/heat/heat-wave-duration/Index_Tx75p/) to the normalised grid and make it available in your geoserver instance?

**Comment by RobAndGo** [comment]
> IMHO we don't need the additional hazard maps with 'normalised' indexes (1 to 3, low, medium, high), but just the thresholds (e.g. x = 8 and y = 14)

Yes, that is true. It would also save some work from my side. :-)

@clarity-h2020/data-processing-team One point to add is that the thresholds I used weren't fixed values, but rather, values relative to the baseline (1971-2000). So, if at one place (e.g. Vienna) the baseline maximum heatwave length was 10 days and at another place (Naples) the baseline maximum heatwave length was 15 days, then a "high" hazard level for those places in the future would be >20 days and >30 days, respectively (i.e. increase >100% as I had defined it). This gets around the problem of latitudinal variations in the climate.

However, in keeping with @p-a-s-c-a-l 's idea, in this case one would just need to define the appropriate percentage values for low/medium/high and then have the software calculate e.g. 
100 x [(future layer) - (baseline layer)] / (baseline layer) 
Then find the points with values e.g. > 100% which would correspond to the high hazard level.
Where the baseline layer contains zeros and the future layer positive values, one could set those points to high - otherwise keep it at low.

The percentage values one uses to define low/medium/high would be different according to the index (e.g. for the flood hazard, the 5-day precipitation index would have 10% and 20% as a better choices for the different hazard levels).

At the moment my choice of these percentage values is not really scientifically based :-( but rather based on producing a map which is not completely everywhere "low" or everywhere "high".

**Comment by p-a-s-c-a-l** [comment]
Thanks for the clarification, yes defining the percentage relative to baseline makes more sense. 
However, how do we define what's low/medium/high in the baseline period?

**Comment by RobAndGo** [comment]
>  how do we define what's low/medium/high in the baseline period?

@p-a-s-c-a-l Good question! To date I have just focused on the hazard scale for the future periods. 
We are currently having some good discussions on how to define low/medium/high in the baseline period and I'll comment further on this when we have come to an agreement.

My **personal opinion** is that we omit this classification for the baseline period and just show an absolute value. My reason for this is following - what happens if a user sees that their hazard level for the current climate is "high", but life is going on without problem, buildings are not crumbling down, infrastructure is functioning, and everything is good. Then, if the hazard level for the future period (e.g. 2041-2070) period is also "high",  how does the user react? I would guess they would be of the opinion that they don't need to do anything, as the current hazard level is "high" and nothing bad is happening.

**Comment by p-a-s-c-a-l** [comment]
> at we omit this classification for the baseline period and just show an absolute value

Ok, agreed!

@luis-meteogrid 
Could you please make the HW hazard (sftp://5.79.69.49/clarityftp/europe/hazard_indices/heat/heat-wave-duration/Index_Tx75p/) available in your geoserver instance (in normalised grid via CSW and WMS + simple styling?

**Comment by RobAndGo** [comment]
@p-a-s-c-a-l 
OK, we (@mzuvela @astridkainz @claudiahahn) finally have a consensus.

1. The low/medium/high in the baseline period will/can be defined relative to all values of the index across Europe (i.e. a comparison across space). Such a method has also been used in the BRIGAID project (Deliverable 5.1, pages 15-16) in the assessment of their baseline climate. 

One thing to note is that this **will only work** with indices defined with **non-constant** threshold values! For example, using our Tx75p example which uses a percentile value as a threshold is OK, as this value varies according to location. Here is a plot showing the absolute values of Tx75p. Just by eyeballing it, the colours deep-orange/red would be “high”, white-yellow “medium” and blues “low” hazard level.
![2018-12-06_113339](https://user-images.githubusercontent.com/45385637/49584732-7f215b00-f95c-11e8-9e1d-a6ebdadd84bc.png)

However, using the index "number of summer days" will not work, since a summer day is defined as a day with the maximum temperature > 25°C (i.e. a fixed value) - in this case southern (northern) Europe will always register a high (low) hazard level.
![2018-12-06_135432](https://user-images.githubusercontent.com/45385637/49585378-7af63d00-f95e-11e8-879f-ed969a1132f6.png)

2. If point 1 is implemented, then the table defined by @astridkainz in https://github.com/clarity-h2020/data-package/issues/8#issuecomment-444487538 will become complicated, as the terms low/medium/high for the future scenarios **are not the same** as the terms for low/medium/high for the baseline climate. To be precise, the future climate will need to be defined as "low change/medium change/high change" with the emphasis on the word "change" relative to the baseline climate.

3. Although we have a lot of different climate indices that we set out to calculate, not all need to be represented in a hazard table form. The idea is that we can calculate the hazard tables only for those indices that contain non-fixed threshold values, and keep the other indices for graphical plots or for processing which the methods of PLINIVS may require. The problem with calculating the hazard table for a lot of heat indices is that there is the risk of conflict between the results - e.g. if Tx75p gives a high change hazard level for 2041-2070 but summer days shows a low change hazard level, what should the user do?

**Comment by humerh** [comment]
I want to refer to my comment at:
https://github.com/orgs/clarity-h2020/teams/data-processing-team/discussions/1?from_comment=15#discussion-1-comment-15

If the hazard data are provided in the way, which were shown in the example "clarity:consecutive_max_heat" at the Geoserver "http://5.79.69.33:8080/geoserver" we are very lucky.
This example shows an WCS Interface and gives me the data in the raster size of 500m.

This example demonstarates also, how to extract only the cell data of the Project area.

I hope, that Atos and Meteogrid can provide all Hazard data layers in this way.

**Comment by humerh** [comment]
The old layer "clarity:consecutive_max_heat" has been removed.

The new layer is now called: clarity:consecutive_heat_days_raster_12km

Please try the following links:

WCS-Call:
~http://5.79.69.33:8080/geoserver/wcs?SERVICE=WCS&REQUEST=GetCoverage&VERSION=2.0.1&CoverageId=clarity:consecutive_heat_days_raster_12km&subset=X(4660000,4700000)&subset=Y(1910000,1990000)&SUBSETTINGCRS=http://www.opengis.net/def/crs/EPSG/0/3035&format=text/plain~

WMS-Call:
~http://5.79.69.33:8080/geoserver/clarity/wms?service=WMS&version=1.1.0&request=GetMap&layers=clarity%3Aconsecutive_heat_days_raster_12km&bbox=4660000,1910000,4700000,1990000&width=500&height=500&srs=EPSG:3035&format=image/png~

**Comment by p-a-s-c-a-l** [comment]
@humerh Please don't use the ATOS instance (5.79.69.33) anymore for HC & EE (we might still use it for "[background layers](https://github.com/clarity-h2020/data-package/issues/5)" that are *input* for to HC-LE), please use the METEOGRID instance instead: https://clarity.meteogrid.com/geoserver/

@negroscuro Please remove the HC layers to avoid further confusion 

@luis-meteogrid please provide the [HC](https://github.com/clarity-h2020/data-package/issues/8#issuecomment-444859213) and [EE](https://github.com/clarity-h2020/data-package/issues/10) layers on your geoserver instance

Thanks!

**Comment by humerh** [comment]
I need help:
If I call the site https://clarity.meteogrid.com/geoserver/ I get immediately a ERR_CONNECTION_RESET.
Does someone know the reason?

**Comment by ghilbrae** [comment]
Example of access via WCS (GetCapabilities):

https://clarity.meteogrid.com/geoserver/clarity/wcs?service=wcs&version=1.0.0&request=GetCapabilities&namespace=clarity

**Comment by ghilbrae** [comment]
After talking with @luis-meteogrid regarding the Calculation of the Local Effects Layers. We have everything ready to perform this calculation but we still need the inputs from the layers that @negroscuro is calculating and also some clarifications from PLINIUS (@stefanon ). We will try to iron out all the details in the following days.

**Comment by RobAndGo** [comment]
Here an example of the current colour scaling for low/medium/high for the same heatwave index shown above (Tx75p).
Top-left panel = baseline climate 1971-2000
Top-right panel = future scenario 2071-2100 RCP2.6
Bottom-left panel = future scenario 2071-2100 RCP4.5
Bottom-right panel = future scenario 2071-2100 RCP8.5
Note that the colour scaling for the three future scenarios refer to **changes** in Tx75p from the baseline climate. The colour scaling for the baseline climate refer to the **absolute values** in Tx75p. Ideally, one should define this in the image and in the hazard table (e.g. mouseover comments?).
![hazardmaps_tx75p_new](https://user-images.githubusercontent.com/45385637/50143748-b45b7080-02ad-11e9-9241-34905e9eadf2.png)

**Comment by ghilbrae** [comment]
**WCS service to raster data**
_Through QGIS_
- Add layers from a WCS server (https://clarity.meteogrid.com/geoserver/clarity/wcs?service)
![img1](https://user-images.githubusercontent.com/1615745/50154303-49b82e00-02c9-11e9-9053-63f9a67a3e68.png)

- Accept and Connect
![img2](https://user-images.githubusercontent.com/1615745/50154323-589ee080-02c9-11e9-9bc9-ac0fb1802b15.png)

- Select layers and add
![img3](https://user-images.githubusercontent.com/1615745/50154336-63f20c00-02c9-11e9-835a-c9d7cd251979.png)

The data has been accessed. This enables viewing and consulting them.
To operate with the layer, it must be downloaded to your computer. Access the options of the layer by clicking on it with the right button. Select option "**save as ...**"
![img4](https://user-images.githubusercontent.com/1615745/50154368-7409eb80-02c9-11e9-87d6-9eb3ce8b3b67.png)

- Indicate output name and GeoTIFF format
![img5](https://user-images.githubusercontent.com/1615745/50154403-871cbb80-02c9-11e9-816a-cf027b5a55be.png)

**WFS service to vectorial data**
_Through QGIS_
It's the same process. In this case, a new connection to WFS data must be created though:
https://clarity.meteogrid.com/geoserver/Clarity-DC4/wfs?service

Note that, for this example, access to the DC4 workspace is used since it contains vector data.

**Comment by negroscuro** [comment]
> After talking with @luis-meteogrid regarding the Calculation of the Local Effects Layers. We have everything ready to perform this calculation but we still need the inputs from the layers that @negroscuro is calculating and also some clarifications from PLINIUS (@stefanon ). We will try to iron out all the details in the following days.

Regarding input layers, what else do you need?

**Comment by p-a-s-c-a-l** [comment]
As agreed with @humerh (Hazard) Events for whole Europe will be served from EMIKAT API! The Data Package has to be updated accordingly. The EMIKAT API for hazard events will be accessed by parametrised URLs. Parameters are project id (=study id) and study area bbox. EMIKAT will then return the relevant events for the table component (preferably in JSON or CSV) and probably also for the Map Component (WMS). 

We need only one Events resource per Hazard. The resource contains two different URLs (references), one for map request (WMS) and one for table data (REST/JSON). The URLs support parameters e.g. `$studyId` and `$studyArea` which are replaced by the ReactJS Components (table and map) by actual values extracted from the study context (obtained via Drupal JSON API).

Current Hazard Indexes, which are not used directly for Impact Calculation, still remain part of the Data Packages and are shown on the map to prove additional info for users.

The Data Package / Hazard Resources has to be updated accordingly once @humerh provided sample, request URIs for the [EMIKAT API](https://github.com/clarity-h2020/emikat/issues/11).

**Comment by maesbri** [comment]
@p-a-s-c-a-l , @humerh can you post here an example of the url API so I can have a look at it and update the corresponding resources in the data package?

**Comment by p-a-s-c-a-l** [comment]
All ZAMG hazard layers are broken. See https://github.com/clarity-h2020/data-package/issues/41#issuecomment-522985208

**Comment by DenoBeno** [comment]
If I understand this correctly, the indices of the 
"Maximum consecutive days (summer) 75th percentile, emissions scenario (rcp85), period (2071-2100), ensemble mean" type are:

1. supposed to  show the difference in the number of consecutive days where the temperature is above some threshold for the future scenarios as compared with the baseline scenario?
2. This threshold temperature is different for each area, so it could be e.g. 30°C in Vienna and 40°C in Naples.

This makes sense to me, but I don't understand some things:

1. This description of the resource seems a it misleading to me.

> Maximum number of days per year with a mean air temperature at 2 m above ground above the 75th percentile during summer months (Apr-Sep) for the rcp85 emissions scenario in the 2071-2100 period (ensemble mean)


Should this be:

> Maximum number of _consecutive_ days per year with a mean air temperature above treshold during summer months (Apr-Sep) for the rcp85 emissions scenario in the 2071-2100 period (ensemble mean)
> - Threshold is defined as the 75th percentile of the summer temperatures that were recorded in the same area in the baseline period y1-y2
> - Temperature is measured in the shadow, at 2 m above ground.

2. What is shown in the baseline data set? It doesn't look very ueful to me
![image](https://user-images.githubusercontent.com/2961790/66351835-a66efd00-e95e-11e9-8f26-11de48639e67.png)

3. Why is the scale chosen to show up to 50 additional days, when even for RCP 85 and end of the century the change is never even nearly as big as this? I believe there is exactly one point where the difference is around 30 days in the whole Europe. And only in RCP85 scenario => all the maps are just blue in blue.

![image](https://user-images.githubusercontent.com/2961790/66352097-3ad95f80-e95f-11e9-8e88-20703e75a369.png)

**Comment by p-a-s-c-a-l** [comment]
AFAIR there is a reason for this, I think @RobAndGo can explain it.

**Comment by RobAndGo** [comment]
I think the problem was that the colour scale is automatically generated based on the lowest and highest values from the dataset. It could be that there are single pixels which have extreme (unrealistic?) values of 50. I think I suggested in another comment that perhaps the colour scaling should be based on only the 75% of the maximum value in the dataset. 

Alternatively, I could filter remove such values myself by cutting them off at a predefined limit.

It should be noted that this index was originally planned to be used in the calculations of impact. However, due to the change in the definition of impact at the Vienna plenary, this index is not really needed and thus not that important anymore. 

I'll look into it further.

**Comment by p-a-s-c-a-l** [comment]
> I think I suggested in another comment that perhaps the colour scaling should be based on only the 75% of the maximum value in the dataset.

Right, now I remember. Maybe @LauraMTG could modify the SLD accordingly?

**Comment by ghilbrae** [comment]
The scale of the data is not generated on-the-fly, it is a static scale that we have to create ourselves. I don't remember why we chose those specific values, probably based on what max and min values we found on the files. We can change that scale with whatever set of values you deem more appropriate.

Just as an example, here you have the definition we are using for the Tx75p_consecutive_max_EUR-11_ICHEC-EC-EARTH_rcp85  layers:

```xml
<ColorMap>
              <ColorMapEntry color="#ffffff" quantity="-1" label="# days" />
              <ColorMapEntry color="#fff" quantity="0" label="0" />
              <ColorMapEntry color="#7b41f7" quantity="6" label="6" />
              <ColorMapEntry color="#425dff" quantity="12" label="12" />
              <ColorMapEntry color="#39b2ff" quantity="18" label="18" />
              <ColorMapEntry color="#39ffde" quantity="24" label="24" />
              <ColorMapEntry color="#8cff39" quantity="30" label="30" />
              <ColorMapEntry color="#ffff42" quantity="36" label="36" />
              <ColorMapEntry color="#ffb24a" quantity="42" label="42" />
              <ColorMapEntry color="#ff4d39" quantity="48" label="48" />
              <ColorMapEntry color="#ad0000" quantity="54" label="54" />
              <ColorMapEntry color="#630000" quantity="60" label="60" />
</ColorMap>
```

**Comment by DenoBeno** [comment]
OK, here is what I would propose:

1) Get rid of the blue color that appears twice in the scale.

![image](https://user-images.githubusercontent.com/2961790/66551880-9adf2a00-eb48-11e9-8f06-f14d4539450e.png)

these two blues are very difficult to distinguish on a map. This should IMO be changed for all maps.

2) choose the 0-something% (e.g. 0-75%) scale, not 0-100% as proposed by Pascal. Not sure if this should be 75%, 8ß% or something else, but this is IMO a good idea. 

I don't think that it matters that much if I get +30 or +50 more consecutive hot days than what I had before. Semantics of this is still "ups, that's much more than we used to have". And if this happens on just a few areas in Europe, we shouldn't be concentrating on it. What's much more interesting to me is if in my city we get +50 days and in another they get +15 days...

Unfortunately, this probably works the best for "relative" indicators, where data is relative to historical, less well for the absolute ones. The only relative indicator that we use atm. is the number of consecutive days above 75% threshold.

@RobAndGo : what is actually shown on the "maximum consecutive days" historical? Is this just zero everywhere?
![image](https://user-images.githubusercontent.com/2961790/66552790-3b821980-eb4a-11e9-87b3-f471d951221a.png)

**Comment by RobAndGo** [comment]
No, there is some structure over Europe. When one plots the data from 0->(max value), one gets:
![2019-10-11_113800](https://user-images.githubusercontent.com/45385637/66641837-cda62280-ec1b-11e9-8f8b-15bfd8926db4.png)

But limiting the range between (min value)->20, one can see that there is something meaningful there:
![2019-10-11_113836](https://user-images.githubusercontent.com/45385637/66641884-e1518900-ec1b-11e9-9dbc-9dbf242161e4.png)

The problem with this index is that the values over water are higher than over land - the water temperature stays constantly warm in summer and is more stable, thus producing more days where the maximum temperature exceeds the 75th percentile. Thus the island coastal regions of Greece, Croatia, Italy not masked out will skew the colour scale. This was why I used the original mask to omit these problematic regions. 

However, if it is possible to plot the colour scale to just 75% of the maximum value, maybe this could solve the problem.

**Comment by LauraMTG** [comment]
Ok @DenoBeno and @RobAndGo 

The solution then is to create new legends with the following criteria:
1-More intervals for the set of low values.
2-New colors associated to each interval.
3- Lower legend maxima, e.g. 75% of the data range.

This may apply to several "type legends" which in turn apply to a set of layers. However, each layer cannot have a specific legend since it would be necessary to create 300 legends.

If this is a possible solution, I will proceed with it as follows

**Comment by DenoBeno** [comment]
Not sure what the story with 300 legends is, but it's IMO a good idea to
keep the scale for a group of similar layers the same. Otherwise they can't
be visually compared.

**Comment by RobAndGo** [comment]
@DenoBeno is right and is something I should have mentioned earlier ![foreheadslap](https://user-images.githubusercontent.com/45385637/66735604-1aca0480-ee67-11e9-810b-5b7558ad6c6e.gif)

When comparing the scenarios one needs to use the same scale/legend. As a suggestion, one could fix the colour scale to that from the **RCP45 2041-2070 scenario**. This is approximately the middle of the possibilities, whereby the results from RCP26 and earlier time periods will appear lower, while those results from RCP85 and later time periods will appear higher.

**Comment by LauraMTG** [comment]
Ok @DenoBeno and @RobAndGo 

We are in the process of correcting the mask of all HI layers. This can alter some values that are presented so I suggest to fix the legends later.
We will elaborate a standard legend for each RCP45 2041-2070 that will be applied to the rest of scenes and periods for each HI set and we will check that this solves the visualization of the data, if it seems suitable to them.

**Comment by DenoBeno** [comment]
I have opened a new issue for data color coding/map scale. Please see https://github.com/clarity-h2020/data-package/issues/53.

**Comment by p-a-s-c-a-l** [comment]
HC Heat Layers available for 1st data package.

**Comment by p-a-s-c-a-l** [comment]
We have to add Pluvial Flood HC resources. See https://github.com/clarity-h2020/local-effects/issues/9#issuecomment-564047414

**Comment by p-a-s-c-a-l** [comment]
A draft template resource for pluvial flood that uses variables is available [here](https://csis.myclimateservice.eu/node/2197/). Map Visualisation isn't 100% working yet as we had to introduce a lot of [accidental complexity](https://www.nutshell.com/blog/accidental-complexity-software-design/) into the codebase due to incoherent [variable meanings](https://github.com/clarity-h2020/csis/issues/101#issuecomment-565025875).

**Comment by p-a-s-c-a-l** [comment]
Including this one, there are now three issues regarding the Pluvial Floods Input layers (https://github.com/clarity-h2020/data-package/issues/54 and https://github.com/clarity-h2020/local-effects/issues/9), so closing this one.
